name: Publish Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Install dependencies
      run: bun install --frozen-lockfile
      
    - name: Compile TypeScript
      run: bun run compile
      
    - name: Package extension
      run: bun run package
      
    - name: Publish to Visual Studio Marketplace
      run: bun run publish
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
        
    - name: Upload VSIX as artifact
      uses: actions/upload-artifact@v4
      with:
        name: extension-package
        path: '*.vsix' 